// Generated by Gatling Recorder HAR Converter from output/har/meta-functional-flow.har.
// Reference only: this file preserves the instructor-aligned HAR conversion trace.
// Jenkins and local evidence runners use ../MetaSimulation.scala, the cleaned
// maintained version of this HAR-derived flow.

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulationFromHar extends Simulation {

	val httpProtocol = http
		.baseUrl("http://51.84.219.74:8080")
		.disableFollowRedirect
		.disableAutoReferer
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7")
		.acceptEncodingHeader("gzip, deflate")
		.upgradeInsecureRequestsHeader("1")
		.userAgentHeader("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/148.0.7778.0 Safari/537.36")

	val headers_1 = Map(
		"Origin" -> "http://51.84.219.74:8080",
		"Referer" -> "http://51.84.219.74:8080/yonatan-csasznik-yoed-halberstam-niv-levin/")



	val scn = scenario("RecordedSimulationFromHar")
		.exec(http("request_0")
			.get("/yonatan-csasznik-yoed-halberstam-niv-levin/"))
		.pause(687 milliseconds)
		.exec(http("request_1")
			.post("/yonatan-csasznik-yoed-halberstam-niv-levin/index.jsp")
			.headers(headers_1)
			.formParam("nameInput", "Yonatan"))
		.exec(http("request_2")
			.get("/yonatan-csasznik-yoed-halberstam-niv-levin/"))
		.pause(595 milliseconds)
		.exec(http("request_3")
			.post("/yonatan-csasznik-yoed-halberstam-niv-levin/index.jsp")
			.headers(headers_1)
			.formParam("nameInput", ""))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
