#!/usr/bin/env sh
set -eu

PROJECT_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)
SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/MetaSimulation.scala"
REFERENCE_SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/reference/RecordedSimulationFromHar.scala"

assert_contains() {
  pattern="$1"
  if ! grep -Fq -- "$pattern" "$SIMULATION"; then
    printf 'Expected Gatling simulation to contain: %s\n' "$pattern" >&2
    exit 1
  fi
}

assert_not_contains() {
  pattern="$1"
  if grep -Fq -- "$pattern" "$SIMULATION"; then
    printf 'Expected Gatling simulation not to contain: %s\n' "$pattern" >&2
    exit 1
  fi
}

assert_contains 'global.failedRequests.count.lt(1)'
assert_contains 'constantConcurrentUsers(intEnv("GATLING_LOAD_USERS", 5)).during(300.seconds)'
assert_contains 'rampConcurrentUsers(intEnv("GATLING_STRESS_START_USERS", 5))'
assert_contains 'constantConcurrentUsers(intEnv("GATLING_MAX_USERS", 5))'
assert_contains '.formParam("nameInput", "Yonatan")'
assert_contains '.formParam("nameInput", "")'
assert_not_contains 'global.failedRequests.percent.lt(5)'
assert_not_contains 'global.responseTime.percentile3.lte(2000)'
assert_not_contains 'constantUsersPerSec'
assert_not_contains 'rampUsersPerSec'
assert_not_contains 'incrementUsersPerSec'

if [ ! -s "$REFERENCE_SIMULATION" ]; then
  printf 'Expected HAR converter reference simulation at %s\n' "$REFERENCE_SIMULATION" >&2
  exit 1
fi

grep -Fq 'Generated by Gatling Recorder HAR Converter from output/har/meta-functional-flow.har.' "$REFERENCE_SIMULATION"
grep -Fq 'class RecordedSimulationFromHar extends Simulation' "$REFERENCE_SIMULATION"
grep -Fq '.post("/yonatan-csasznik-yoed-halberstam-niv-levin/index.jsp")' "$REFERENCE_SIMULATION"
grep -Fq '.formParam("nameInput", "Yonatan")' "$REFERENCE_SIMULATION"
grep -Fq '.formParam("nameInput", "")' "$REFERENCE_SIMULATION"

printf '%s\n' 'Gatling assertion policy checks passed'
