#!/usr/bin/env sh
set -eu

PROJECT_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)
HAR_DOC="$PROJECT_ROOT/docs/har-scenario.md"
GATLING_DOC="$PROJECT_ROOT/docs/gatling.md"
COMPLIANCE_DOC="$PROJECT_ROOT/rules/compliance.md"
REFERENCE_SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/reference/RecordedSimulationFromHar.scala"
MAINTAINED_SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/MetaSimulation.scala"

assert_contains() {
  file="$1"
  pattern="$2"
  if ! grep -Fq -- "$pattern" "$file"; then
    printf 'Expected %s to contain: %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

assert_not_contains() {
  file="$1"
  pattern="$2"
  if grep -Fq -- "$pattern" "$file"; then
    printf 'Expected %s not to contain: %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

assert_contains "$HAR_DOC" 'Gatling does not load this HAR at runtime.'
assert_contains "$GATLING_DOC" 'Gatling does not load the HAR file at runtime.'
assert_contains "$COMPLIANCE_DOC" 'Gatling does not load the HAR at runtime in this project.'
assert_contains "$REFERENCE_SIMULATION" 'Generated by Gatling Recorder HAR Converter from output/har/meta-functional-flow.har.'
assert_contains "$REFERENCE_SIMULATION" '.formParam("nameInput", "Yonatan")'
assert_contains "$REFERENCE_SIMULATION" '.formParam("nameInput", "")'
assert_contains "$MAINTAINED_SIMULATION" '.formParam("nameInput", "Yonatan")'
assert_contains "$MAINTAINED_SIMULATION" '.formParam("nameInput", "")'

assert_not_contains "$COMPLIANCE_DOC" 'constantUsersPerSec'
assert_not_contains "$COMPLIANCE_DOC" 'rampUsersPerSec'

printf '%s\n' 'Gatling HAR alignment checks passed'
