#!/usr/bin/env sh
set -eu

PROJECT_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)
SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/MetaSimulation.scala"
REFERENCE_SIMULATION="$PROJECT_ROOT/src/gatling/user-files/simulations/reference/RecordedSimulationFromHar.scala"

assert_contains() {
  pattern="$1"
  if ! grep -Fq -- "$pattern" "$SIMULATION"; then
    printf 'Expected Gatling simulation to contain: %s\n' "$pattern" >&2
    exit 1
  fi
}

assert_not_contains() {
  pattern="$1"
  if grep -Fq -- "$pattern" "$SIMULATION"; then
    printf 'Expected Gatling simulation not to contain: %s\n' "$pattern" >&2
    exit 1
  fi
}

assert_contains 'global.failedRequests.count.lt(1)'
assert_contains 'private def intEnv(name: String, defaultValue: => Int): Int'
assert_contains 'private val scn = scenario("Meta JSP HAR-derived flow")'
assert_contains 'private def levelScenario(level: Int) = scenario(s"Meta JSP HAR-derived flow max-limit ${level} users").exec(harDerivedFlow)'
assert_contains 'rampConcurrentUsers(0).to(loadUsers).during(60.seconds)'
assert_contains 'constantConcurrentUsers(loadUsers).during(180.seconds)'
assert_contains 'rampConcurrentUsers(loadUsers).to(0).during(60.seconds)'
assert_contains 'val stressStartUsers = intEnv("GATLING_STRESS_START_USERS", 10)'
assert_contains 'val stressLevels = staircaseLevels(stressStartUsers, stressTargetUsers, "GATLING_STRESS")'
assert_contains 'math.round((targetUsers - startUsers).toDouble * level / 4.0).toInt'
assert_contains 'constantConcurrentUsers(stressLevels(0)).during(60.seconds)'
assert_contains 'constantConcurrentUsers(stressLevels(4)).during(60.seconds)'
assert_not_contains 'must divide evenly into four staircase steps'
assert_contains 'private def steppedLevels(baseUsers: Int, limitUsers: Int, stepUsers: Int): Seq[Int]'
assert_contains 'GATLING_MAX_LIMIT_USERS must be greater than or equal to GATLING_MAX_BASE_USERS'
assert_contains 'val maxBaseUsers = intEnv("GATLING_MAX_BASE_USERS", intEnv("GATLING_MAX_USERS", 5))'
assert_contains 'val maxStepUsers = intEnv("GATLING_MAX_STEP_USERS", 5)'
assert_contains 'val maxLimitUsers = intEnv("GATLING_MAX_LIMIT_USERS", maxBaseUsers)'
assert_contains 'val levels = steppedLevels(maxBaseUsers, maxLimitUsers, maxStepUsers)'
assert_contains 'nothingFor((index * maxDurationSeconds).seconds)'
assert_contains 'constantConcurrentUsers(level).during(maxDurationSeconds.seconds)'
assert_contains 'setUp(populations: _*)'
assert_not_contains 'GATLING_MAX_PROFILE_MODE'
assert_not_contains 'case "visual" =>'
assert_not_contains 'maxVisualIncrementCount'
assert_not_contains 'incrementConcurrentUsers(maxStepUsers)'
assert_not_contains '.startingFrom(maxBaseUsers)'
assert_contains '.formParam("nameInput", "Yonatan")'
assert_contains '.formParam("nameInput", "")'
assert_not_contains 'rampConcurrentUsers(maxUsers)'
assert_not_contains 'visualSteppedLevels'
assert_not_contains '5 selected levels'
assert_not_contains 'global.failedRequests.percent.lt(5)'
assert_not_contains 'global.responseTime.percentile3.lte(2000)'
assert_not_contains 'constantUsersPerSec'
assert_not_contains 'rampUsersPerSec'
assert_not_contains 'incrementUsersPerSec'
assert_not_contains 'scenarioFor(300)'
assert_not_contains '.during(durationSeconds.seconds)'
assert_not_contains 'constantConcurrentUsers(maxUsers).during(maxDurationSeconds.seconds)'

if [ ! -s "$REFERENCE_SIMULATION" ]; then
  printf 'Expected HAR converter reference simulation at %s\n' "$REFERENCE_SIMULATION" >&2
  exit 1
fi

grep -Fq 'Generated by Gatling Recorder HAR Converter from output/har/meta-functional-flow.har.' "$REFERENCE_SIMULATION"
grep -Fq 'class RecordedSimulationFromHar extends Simulation' "$REFERENCE_SIMULATION"
grep -Fq '.post("/yonatan-csasznik-yoed-halberstam-niv-levin/index.jsp")' "$REFERENCE_SIMULATION"
grep -Fq '.formParam("nameInput", "Yonatan")' "$REFERENCE_SIMULATION"
grep -Fq '.formParam("nameInput", "")' "$REFERENCE_SIMULATION"

printf '%s\n' 'Gatling assertion policy checks passed'
